### ISSUE TITLE
по стажировке в KODE

### ISSUE THREAD

**Issue by Egorius1979** [StanleySB/Pokemon-app-react-hooks-#1]
Добрый день!

Можно узнать - вас взяли на стажировку? Мне просто написали, что не готовы пригласить, без всяких технических объяснений в чём причина. Просто интересно, как у вас с этим делом сложилось.
Спасибо!

**Comment by StanleySB** [comment]
Добрый день, да, на стажировку взяли

**Comment by Egorius1979** [comment]
Понял, спасибо ,что ответили. Ну что ж, тогда удачи - чтобы всё сложилось!
